name: CI Pipeline

on:
  push:
    branches:
      - main  # Run on pushes to the main branch
  pull_request:
    branches:
      - main  # Run on pull requests to the main branch

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Change to your project's Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 isort mypy pytest  # Add other dependencies as needed
          pip install -r requirements-dev.txt  # If you use a requirements file

      # Step 4: Run flake8
      - name: Run flake8
        run: trace_logger/ tests/  # Adjust the target directory if needed

      # Step 5: Run isort check
      - name: Run isort check
        run: isort trace_logger/ tests/ --check-only

      # Step 6: Run mypy
      - name: Run mypy
        run: mypy trace_logger/ tests/  # Adjust the target directory if needed

      # Step 7: Run tests
      - name: Run tests
        run: pytest tests/ -vv  # Adjust the command if needed (e.g., specify test directory)
