name: CI Pipeline

on:
  push:
    branches:
      - main  # Run on pushes to the main branch
  pull_request:
    branches:
      - main  # Run on pull requests to the main branch

jobs:
  # Job 1: Linting with flake8
  lint-flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: flake8 secure_logs/ tests/

  # Job 2: Import sorting with isort
  lint-isort:
    runs-on: ubuntu-latest
    needs: lint-flake8
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install isort
        run: |
          python -m pip install --upgrade pip
          pip install isort

      - name: Run isort check
        run: isort secure_logs/ tests/ --check-only

  # Job 3: Static type checking with mypy
  lint-mypy:
    runs-on: ubuntu-latest
    needs: lint-isort
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install mypy and types dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy
          pip install types-starlette  # Install type hints for Starlette
          pip install -r requirements-dev.txt  # Include your dev requirements if applicable

      - name: Run mypy
        run: mypy secure_logs/ tests/

  # Job 4: Run tests with pytest
  run-tests:
    runs-on: ubuntu-latest
    needs: lint-mypy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements-dev.txt  # If you have a dev requirements file

      - name: Run tests
        run: pytest tests/ -vv
